apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: netapi
  name: pod-service
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    run: netapi
  type: LoadBalancer
status:
  loadBalancer: {}
