apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: netapi
  name: netapi
spec:
  containers:
  - image: hcobian/netapi:1.0.0
    name: netapi
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
